[tool.poetry]
name = "autotask"
version = "0.1.0"
description = ""
authors = ["wuyongbo <wdhwyb@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyperclip = "^1.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
